# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VogChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VogChallenge
  pod 'Alamofire', '~> 5.2'
  pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'

  target 'VogChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VogChallengeUITests' do
    # Pods for testing
  end

end
